import type { UnidadMedida } from '@/types/api'

export const UNIDAD_LABELS: Record<UnidadMedida, string> = {
  und: 'Unidad',
  kg: 'Kilogramo',
  g: 'Gramo',
  m: 'Metro',
  m2: 'Metro²',
  m3: 'Metro³',
  l: 'Litro',
  ml: 'Mililitro',
  gal: 'Galón',
  bolsa: 'Bolsa',
  caja: 'Caja',
  rollo: 'Rollo',
  par: 'Par',
  juego: 'Juego',
  docena: 'Docena',
  ciento: 'Ciento',
  medio_ciento: 'Medio ciento',
  millar: 'Millar',
  medio_millar: 'Medio millar',
  balde: 'Balde',
  galonera: 'Galonera',
  cilindro: 'Cilindro',
  varilla: 'Varilla',
  plancha: 'Plancha',
  tubo: 'Tubo',
  pieza: 'Pieza',
  global: 'Global',
}

export const UNIDAD_ABBR: Record<UnidadMedida, string> = {
  und: 'und',
  kg: 'kg',
  g: 'g',
  m: 'm',
  m2: 'm²',
  m3: 'm³',
  l: 'L',
  ml: 'mL',
  gal: 'gal',
  bolsa: 'bolsa',
  caja: 'caja',
  rollo: 'rollo',
  par: 'par',
  juego: 'juego',
  docena: 'doc',
  ciento: 'cto',
  medio_ciento: '½ cto',
  millar: 'mllr',
  medio_millar: '½ mllr',
  balde: 'balde',
  galonera: 'galonera',
  cilindro: 'cilindro',
  varilla: 'varilla',
  plancha: 'plancha',
  tubo: 'tubo',
  pieza: 'pza',
  global: 'global',
}

export const UNIDAD_OPTIONS = Object.entries(UNIDAD_LABELS) as [
  UnidadMedida,
  string,
][]

